### PR TITLE
Fixed formatting, edited a bit from my part

### PR DESCRIPTION
**Pull request by Wesdcv**
Added auto-build .pdf via GitHub Actions as well

### CODE REVIEW

**Comment by ZuxiGIT** [comment]
Can you squash commits related to main.yml into one, please?

**Comment by ZuxiGIT** [comment]
Also it's better to leverage already configured Dockerfile in github actions, because it will allow to keep github actions and configured docker container in a consistent state

**Comment by Wesdcv** [comment]
> Can you squash commits related to main.yml into one, please?

If you guide me on how to, i think github doesn't provide such a feature on PRs.


> Also it's better to leverage already configured Dockerfile in github actions, because it will allow to keep github actions and configured docker container in a consistent state

It could be done, of course, but i'm unsure about adding an additional computational overhead to actions (installing docker, pulling images) - since the free plan of github action allows for only a bunch of runtime minutes. The base image is pretty old as well, but i'll look into it to check if anything could be made more efficient.

**Comment by ZuxiGIT** [comment]
> If you guide me on how to, i think github doesn't provide such a feature on PRs.

Check out https://www.hatica.io/blog/squashing-git-commits/ .
After local branch modification you can force push it to remote repository

**Comment by ZuxiGIT** [comment]
> since the free plan of github action allows for only a bunch of runtime minutes

AFAIK, Github actions themselfs suggests to configure docker image.
Check out: https://dev.to/sahanonp/setup-docker-for-integration-testing-in-github-action-39fn

**Comment by Wesdcv** [comment]
Did the 2nd request, regarding the 1st one i believe you can choose squash merge option when approving and all mine commits would be merged as one. I can PR 6.2 summarization as a separate request if that's an issue. Would that be fine with you?

**Comment by ZuxiGIT** [comment]
Don't bother. LGTM

**Pull request merged**
